-- AlterTable
ALTER TABLE `room` ADD COLUMN `room` VARCHAR(191) NOT NULL DEFAULT CONCAT('room', LPAD(FLOOR(RAND() * 10000000000), 7, '0')),
    ADD COLUMN `startus` ENUM('VACANT', 'OCCUPIED') NOT NULL DEFAULT 'OCCUPIED';

-- AlterTable
ALTER TABLE `user` MODIFY `usr` VARCHAR(191) NOT NULL DEFAULT CONCAT('usr', LPAD(FLOOR(RAND() * 10000000000), 7, '0'));
